token_atomizer:
  :class: :token_atomizer_worker
  :job_key: 'token_atomizer'
  :trigger_args:
    :start: <%= Time.now + 5.seconds %>
collector:
  :class: :collector_worker
  :job_key: 'collector'
  :trigger_args:
    :start: <%= Time.now + 20.seconds %>
